# Generated by Django 2.2.3 on 2019-08-07 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=20)),
                ('profile_image', models.ImageField(default='media/default_image.png', upload_to='')),
                ('is_writer', models.CharField(default='일반', max_length=10)),
                ('writer_name', models.CharField(max_length=20)),
                ('introduction', models.TextField(max_length=200)),
                ('hashtag', models.CharField(max_length=50)),
                ('jenre', models.CharField(max_length=20)),
                ('main_post1', models.TextField(default='')),
                ('main_post2', models.TextField(default='')),
                ('main_post3', models.TextField(default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
