# Generated by Django 2.2.3 on 2019-08-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='subscribe',
            field=models.ManyToManyField(to='account.Account'),
        ),
    ]
