# Generated by Django 2.2.3 on 2019-08-09 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_auto_20190809_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='be_sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='account',
            name='subscribe',
        ),
        migrations.AddField(
            model_name='account',
            name='subscribe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribe', to=settings.AUTH_USER_MODEL),
        ),
    ]
