# Generated by Django 2.2.3 on 2019-08-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20190810_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='be_sub',
        ),
        migrations.RemoveField(
            model_name='account',
            name='subscribe',
        ),
        migrations.AddField(
            model_name='account',
            name='subscribe',
            field=models.ManyToManyField(blank=True, to='account.Account'),
        ),
    ]
